
import type { Event } from './types';

// This mock data is aligned with the new Event model.
// Note: `organizerId` would typically be a UUID corresponding to a user in the database.
export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Summer Music Fest',
    description: 'An outdoor music festival featuring a variety of bands and artists. Enjoy live music, food trucks, and a vibrant atmosphere under the summer sun. Bring your friends and family for an unforgettable weekend of entertainment.',
    date: '2025-09-10T19:00:00.000Z',
    location: 'Annie Kadji Art Gallery',
    artType: 'Performance Art',
    category: 'Performance',
    images: ['https://picsum.photos/600/400'],
    organizerId: 'org-1',
    organizer: 'MusicMakers Inc.',
    price: 25,
    isFeatured: true,
    createdAt: '2025-08-01T10:00:00.000Z',
    updatedAt: '2025-08-01T10:00:00.000Z',
  },
  {
    id: '2',
    title: 'Modern Art Exhibition',
    description: 'Explore a curated collection of modern art from emerging and established artists. The exhibition showcases paintings, sculptures, and interactive installations that challenge perception and inspire creativity.',
    date: '2025-09-15T18:00:00.000Z',
    location: 'artBakery',
    artType: 'Mixed Media',
    category: 'Group Exhibition',
    images: ['https://picsum.photos/600/401'],
    organizerId: 'org-2',
    organizer: 'Artful Curators',
    price: 0,
    createdAt: '2025-08-02T11:30:00.000Z',
    updatedAt: '2025-08-02T11:30:00.000Z',
  },
  {
    id: '3',
    title: 'Gourmet Food Fair',
    description: 'A paradise for food lovers! Sample a wide range of gourmet dishes from local and international chefs. From street food classics to fine dining tasters, there is something for every palate.',
    date: '2025-09-05T14:00:00.000Z',
    location: 'Babungo Museum',
    artType: 'Installation',
    category: 'Workshop',
    images: ['https://picsum.photos/600/402'],
    organizerId: 'org-1',
    organizer: 'TasteBuds Events',
    price: 50,
    createdAt: '2025-08-03T12:00:00.000Z',
    updatedAt: '2025-08-03T12:00:00.000Z',
  },
  {
    id: '4',
    title: 'Community Charity Run',
    description: 'Join us for a 5K charity run to support local community projects. It is a great way to stay active, meet new people, and make a positive impact. All ages and fitness levels are welcome.',
    date: '2025-09-20T09:00:00.000Z',
    location: 'Baham Museum',
    artType: 'Performance Art',
    category: 'Performance',
    images: ['https://picsum.photos/600/403'],
    organizerId: 'org-3',
    organizer: 'Community First',
    price: 0,
    createdAt: '2025-08-04T14:00:00.000Z',
    updatedAt: '2025-08-04T14:00:00.000Z',
  },
  {
    id: '5',
    title: 'Tech Innovators Conference',
    description: 'A premier event for tech enthusiasts and professionals. Hear from industry leaders, discover the latest trends in technology, and network with peers. Topics include AI, blockchain, and sustainable tech.',
    date: '2025-09-30T10:00:00.000Z',
    location: 'Bandjoun Station',
    artType: 'Digital Art',
    category: 'Panel Discussion',
    images: ['https://picsum.photos/600/404'],
    organizerId: 'org-2',
    organizer: 'FutureTech',
    price: 150,
    isFeatured: true,
    createdAt: '2025-08-05T16:00:00.000Z',
    updatedAt: '2025-08-05T16:00:00.000Z',
  },
  {
    id: '6',
    title: 'Neighborhood Cleanup Day',
    description: 'Let us work together to make our neighborhood a cleaner, greener place. We will provide all the necessary supplies. A great opportunity to volunteer and connect with your neighbors.',
    date: '2025-09-03T11:00:00.000Z',
    location: 'Blackitude Museum',
    artType: 'Installation',
    category: 'Open Studios',
    images: ['https://picsum.photos/600/405'],
    organizerId: 'org-3',
    organizer: 'Green Neighbors',
    price: 0,
    createdAt: '2025-08-06T18:00:00.000Z',
    updatedAt: '2025-08-06T18:00:00.000Z',
  },
    {
    id: '7',
    title: 'Indie Film Screening',
    description: 'Discover the next generation of filmmakers at our indie film screening night. Featuring a selection of short films and documentaries from around the world. Q&A session with directors after the show.',
    date: '2025-09-08T20:00:00.000Z',
    location: 'doual\'art',
    artType: 'Video Art',
    category: 'Screening',
    images: ['https://picsum.photos/600/406'],
    organizerId: 'org-4',
    organizer: 'Cinema Paradiso',
    price: 10,
    createdAt: '2025-08-07T20:00:00.000Z',
    updatedAt: '2025-08-07T20:00:00.000Z',
  },
  {
    id: '8',
    title: 'Local Farmers Market',
    description: 'Shop fresh, locally-grown produce, artisanal cheeses, handmade crafts, and more. Support local farmers and artisans while enjoying the best of what our region has to offer.',
    date: '2025-09-02T12:00:00.000Z',
    location: 'Galerie MAM',
    artType: 'Textile Arts',
    category: 'Art Fair',
    images: ['https://picsum.photos/600/407'],
    organizerId: 'org-5',
    organizer: 'Local Harvest Co-op',
    price: 0,
    createdAt: '2025-08-08T22:00:00.000Z',
    updatedAt: '2025-08-08T22:00:00.000Z',
  },
];