import type { Event } from './types';

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Summer Music Fest',
    description: 'An outdoor music festival featuring a variety of bands and artists. Enjoy live music, food trucks, and a vibrant atmosphere under the summer sun. Bring your friends and family for an unforgettable weekend of entertainment.',
    date: new Date(new Date().setDate(new Date().getDate() + 10)).toISOString(),
    location: 'Central Park',
    category: 'Music',
    imageUrl: 'https://picsum.photos/400/250',
    organizer: 'MusicMakers Inc.',
  },
  {
    id: '2',
    title: 'Modern Art Exhibition',
    description: 'Explore a curated collection of modern art from emerging and established artists. The exhibition showcases paintings, sculptures, and interactive installations that challenge perception and inspire creativity.',
    date: new Date(new Date().setDate(new Date().getDate() + 15)).toISOString(),
    location: 'City Art Gallery',
    category: 'Art',
    imageUrl: 'https://picsum.photos/400/251',
    organizer: 'Artful Curators',
  },
  {
    id: '3',
    title: 'Gourmet Food Fair',
    description: 'A paradise for food lovers! Sample a wide range of gourmet dishes from local and international chefs. From street food classics to fine dining tasters, there is something for every palate.',
    date: new Date(new Date().setDate(new Date().getDate() + 5)).toISOString(),
    location: 'Exhibition Hall',
    category: 'Food',
    imageUrl: 'https://picsum.photos/400/252',
    organizer: 'TasteBuds Events',
  },
  {
    id: '4',
    title: 'Community Charity Run',
    description: 'Join us for a 5K charity run to support local community projects. It is a great way to stay active, meet new people, and make a positive impact. All ages and fitness levels are welcome.',
    date: new Date(new Date().setDate(new Date().getDate() + 20)).toISOString(),
    location: 'Riverside Path',
    category: 'Sports',
    imageUrl: 'https://picsum.photos/400/253',
    organizer: 'Community First',
  },
  {
    id: '5',
    title: 'Tech Innovators Conference',
    description: 'A premier event for tech enthusiasts and professionals. Hear from industry leaders, discover the latest trends in technology, and network with peers. Topics include AI, blockchain, and sustainable tech.',
    date: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
    location: 'Convention Center',
    category: 'Business',
    imageUrl: 'https://picsum.photos/400/254',
    organizer: 'FutureTech',
  },
  {
    id: '6',
    title: 'Neighborhood Cleanup Day',
    description: 'Let us work together to make our neighborhood a cleaner, greener place. We will provide all the necessary supplies. A great opportunity to volunteer and connect with your neighbors.',
    date: new Date(new Date().setDate(new Date().getDate() + 3)).toISOString(),
    location: 'Maple Street Park',
    category: 'Community',
    imageUrl: 'https://picsum.photos/400/255',
    organizer: 'Green Neighbors',
  },
    {
    id: '7',
    title: 'Indie Film Screening',
    description: 'Discover the next generation of filmmakers at our indie film screening night. Featuring a selection of short films and documentaries from around the world. Q&A session with directors after the show.',
    date: new Date(new Date().setDate(new Date().getDate() + 8)).toISOString(),
    location: 'The Grand Cinema',
    category: 'Art',
    imageUrl: 'https://picsum.photos/400/256',
    organizer: 'Cinema Paradiso',
  },
  {
    id: '8',
    title: 'Local Farmers Market',
    description: 'Shop fresh, locally-grown produce, artisanal cheeses, handmade crafts, and more. Support local farmers and artisans while enjoying the best of what our region has to offer.',
    date: new Date(new Date().setDate(new Date().getDate() + 2)).toISOString(),
    location: 'Town Square',
    category: 'Food',
    imageUrl: 'https://picsum.photos/400/257',
    organizer: 'Local Harvest Co-op',
  },
];
