
import type { Event } from './types';

// This mock data is aligned with the new Event model.
// Note: `organizerId` would typically be a UUID corresponding to a user in the database.
export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Douala Rhythms Live',
    description: 'An outdoor music festival featuring a variety of bands and artists. Enjoy live music, food trucks, and a vibrant atmosphere under the summer sun. Bring your friends and family for an unforgettable weekend of entertainment.',
    date: '2025-09-10T19:00:00.000Z',
    location: 'Annie Kadji Art Gallery',
    art_type: 'Performance Art',
    category: 'Performance',
    images: ['https://picsum.photos/600/400'],
    created_by: 'org-1',
    organizer: { name: 'MusicMakers Inc.', email: 'contact@musicmakers.com' },
    price: 2500,
    featured: true,
    created_at: '2025-08-01T10:00:00.000Z',
    updated_at: '2025-08-01T10:00:00.000Z',
  },
  {
    id: '2',
    title: 'Yaoundé Art Now',
    description: 'Explore a curated collection of modern art from emerging and established artists. The exhibition showcases paintings, sculptures, and interactive installations that challenge perception and inspire creativity.',
    date: '2025-09-15T18:00:00.000Z',
    location: 'artBakery',
    art_type: 'Mixed Media',
    category: 'Group Exhibition',
    images: ['https://picsum.photos/600/401'],
    created_by: 'org-2',
    organizer: { name: 'Artful Curators', email: 'info@artfulcurators.com' },
    price: 0,
    created_at: '2025-08-02T11:30:00.000Z',
    updated_at: '2025-08-02T11:30:00.000Z',
  },
  {
    id: '3',
    title: 'Ancestral Echoes: Babungo Masks',
    description: 'A paradise for food lovers! Sample a wide range of gourmet dishes from local and international chefs. From street food classics to fine dining tasters, there is something for every palate.',
    date: '2025-09-05T14:00:00.000Z',
    location: 'Babungo Museum',
    art_type: 'Installation',
    category: 'Workshop',
    images: ['https://picsum.photos/600/402'],
    created_by: 'org-1',
    organizer: { name: 'TasteBuds Events', email: 'contact@tastebuds.com' },
    price: 5000,
    created_at: '2025-08-03T12:00:00.000Z',
    updated_at: '2025-08-03T12:00:00.000Z',
  },
  {
    id: '4',
    title: 'Baham Royal Dance Performance',
    description: 'Join us for a 5K charity run to support local community projects. It is a great way to stay active, meet new people, and make a positive impact. All ages and fitness levels are welcome.',
    date: '2025-09-20T09:00:00.000Z',
    location: 'Baham Museum',
    art_type: 'Performance Art',
    category: 'Performance',
    images: ['https://picsum.photos/600/403'],
    created_by: 'org-3',
    organizer: { name: 'Community First', email: 'contact@communityfirst.org' },
    price: 0,
    created_at: '2025-08-04T14:00:00.000Z',
    updated_at: '2025-08-04T14:00:00.000Z',
  },
  {
    id: '5',
    title: 'Digital Futures at Bandjoun Station',
    description: 'A premier event for tech enthusiasts and professionals. Hear from industry leaders, discover the latest trends in technology, and network with peers. Topics include AI, blockchain, and sustainable tech.',
    date: '2025-09-30T10:00:00.000Z',
    location: 'Bandjoun Station',
    art_type: 'Digital Art',
    category: 'Panel Discussion',
    images: ['https://picsum.photos/600/404'],
    created_by: 'org-2',
    organizer: { name: 'FutureTech', email: 'info@futuretech.com' },
    price: 15000,
    featured: true,
    created_at: '2025-08-05T16:00:00.000Z',
    updated_at: '2025-08-05T16:00:00.000Z',
  },
  {
    id: '6',
    title: 'Reclaimed: Art from Urban Spaces',
    description: 'Let us work together to make our neighborhood a cleaner, greener place. We will provide all the necessary supplies. A great opportunity to volunteer and connect with your neighbors.',
    date: '2025-09-03T11:00:00.000Z',
    location: 'Blackitude Museum',
    art_type: 'Installation',
    category: 'Open Studios',
    images: ['https://picsum.photos/600/405'],
    created_by: 'org-3',
    organizer: { name: 'Green Neighbors', email: 'contact@greenneighbors.org' },
    price: 0,
    created_at: '2025-08-06T18:00:00.000Z',
    updated_at: '2025-08-06T18:00:00.000Z',
  },
    {
    id: '7',
    title: 'Kribi Film Festival Showcase',
    description: 'Discover the next generation of filmmakers at our indie film screening night. Featuring a selection of short films and documentaries from around the world. Q&A session with directors after the show.',
    date: '2025-09-08T20:00:00.000Z',
    location: 'doual\'art',
    art_type: 'Video Art',
    category: 'Screening',
    images: ['https://picsum.photos/600/406'],
    created_by: 'org-4',
    organizer: { name: 'Cinema Paradiso', email: 'info@cinemaparadiso.com' },
    price: 1000,
    created_at: '2025-08-07T20:00:00.000Z',
    updated_at: '2025-08-07T20:00:00.000Z',
  },
  {
    id: '8',
    title: 'Bamenda Crafts & Textiles Fair',
    description: 'Shop fresh, locally-grown produce, artisanal cheeses, handmade crafts, and more. Support local farmers and artisans while enjoying the best of what our region has to offer.',
    date: '2025-09-02T12:00:00.000Z',
    location: 'Galerie MAM',
    art_type: 'Textile Arts',
    category: 'Art Fair',
    images: ['https://picsum.photos/600/407'],
    created_by: 'org-5',
    organizer: { name: 'Local Harvest Co-op', email: 'contact@localharvest.coop' },
    price: 0,
    created_at: '2025-08-08T22:00:00.000Z',
    updated_at: '2025-08-08T22:00:00.000Z',
  },
];
